version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g aws-cdk
      - npm install -g typescript
      - npm i
  build:
    commands:
      - cdk synth eks
      - cdk synth cicd
  post_build:
    commands:
      - >-
        aws cloudformation validate-template --template-body
        file://cdk.out/eks.template.json
      - >-
        aws cloudformation validate-template --template-body
        file://cdk.out/cicd.template.json
artifacts:
  files:
    - cdk.out/eks.template.json
    - cdk.out/cicd.template.json
